#!/bin/bash
adb shell pm install-existing com.motorola.aiservices
adb shell pm install-existing com.motorola.sprint.setupext
adb shell pm install-existing com.android.systemui.auto_generated_rro_vendor__
adb shell pm install-existing com.android.theme.icon.teardrop
adb shell pm install-existing com.dish.wireless.activation
adb shell pm install-existing com.qti.phone
adb shell pm install-existing com.google.android.overlay.modules.permissioncontroller.forframework
adb shell pm install-existing com.motorola.android.providers.settings.overlay.tapwakeoff
adb shell pm install-existing com.motorola.android.provisioning
adb shell pm install-existing com.uscc.ecid
adb shell pm install-existing com.motorola.paks
adb shell pm install-existing com.motorola.wifi.motowifimetrics
adb shell pm install-existing com.qualcomm.qti.cne
adb shell pm install-existing com.metro.minus1
adb shell pm install-existing com.android.systemui.accessibility.accessibilitymenu
adb shell pm install-existing com.android.providers.contacts
adb shell pm install-existing com.motorola.dynamicvolume
adb shell pm install-existing com.google.android.apps.nbu.files
adb shell pm install-existing com.motorola.screenshoteditor
adb shell pm install-existing com.google.android.apps.fitness
adb shell pm install-existing com.android.companiondevicemanager
adb shell pm install-existing com.android.cts.priv.ctsshim
adb shell pm install-existing com.android.phone.overlay.motcommon
adb shell pm install-existing com.motorola.android.server.telecom.overlay.gms.boost
adb shell pm install-existing com.android.providers.downloads
adb shell pm install-existing com.android.bluetoothmidiservice
adb shell pm install-existing com.facebook.appmanager
adb shell pm install-existing com.android.credentialmanager
adb shell pm install-existing com.google.android.printservice.recommendation
adb shell pm install-existing com.google.android.captiveportallogin
adb shell pm install-existing com.google.android.networkstack
adb shell pm install-existing com.android.keychain
adb shell pm install-existing com.motorola.ccc.devicemanagement
adb shell pm install-existing com.google.android.accessibility.switchaccess
adb shell pm install-existing com.google.android.overlay.gmsconfig.asi
adb shell pm install-existing com.google.android.tag
adb shell pm install-existing com.motorola.android.launcher.overlay.retail
adb shell pm install-existing com.motorola.actions.overlay
adb shell pm install-existing com.motorola.gesture
adb shell pm install-existing com.android.shell
adb shell pm install-existing com.google.android.wifi.dialog
adb shell pm install-existing com.google.android.ondevicepersonalization.services
adb shell pm install-existing com.android.bookmarkprovider
adb shell pm install-existing com.motorola.android.networkstack.tethering.overlay.motCommon
adb shell pm install-existing com.dolby.daxservice
adb shell pm install-existing com.motorola.ccc.mainplm
adb shell pm install-existing com.motorola.android.launcher.overlay.cricket.apptray
adb shell pm install-existing com.google.android.apps.docs.editors.slides
adb shell pm install-existing com.motorola.android.providers.chromehomepage
adb shell pm install-existing com.android.sharedstoragebackup
adb shell pm install-existing com.android.imsserviceentitlement
adb shell pm install-existing com.qualcomm.qti.uimGbaApp
adb shell pm install-existing com.android.providers.media
adb shell pm install-existing com.android.providers.calendar
adb shell pm install-existing com.android.providers.blockednumber
adb shell pm install-existing com.google.android.documentsui
adb shell pm install-existing com.motorola.msimsettings
adb shell pm install-existing com.android.proxyhandler
adb shell pm install-existing com.motorola.tmo.settingsext
adb shell pm install-existing com.google.android.overlay.modules.permissioncontroller
adb shell pm install-existing com.android.theme.font.RookeryRegular
adb shell pm install-existing com.android.emergency
adb shell pm install-existing com.google.android.gms.location.history
adb shell pm install-existing com.motorola.ccc.notification
adb shell pm install-existing com.motorola.help
adb shell pm install-existing com.motorola.android.coresettingsext.overlay.doubletap
adb shell pm install-existing com.google.android.apps.googleassistant
adb shell pm install-existing com.motorola.entitlement
adb shell pm install-existing com.qualcomm.location
adb shell pm install-existing com.google.android.gm
adb shell pm install-existing com.android.carrierdefaultapp
adb shell pm install-existing com.android.backupconfirm
adb shell pm install-existing com.motorola.launcherconfig.overlay.cc
adb shell pm install-existing com.motorola.carriersettingsext
adb shell pm install-existing com.google.android.apps.tachyon
adb shell pm install-existing com.google.android.hotspot2.osulogin
adb shell pm install-existing com.spectrum.cm.headless
adb shell pm install-existing com.motorola.safetycenter.resources.overlay
adb shell pm install-existing com.android.mtp
adb shell pm install-existing com.motorola.moto
adb shell pm install-existing com.google.android.apps.magazines
adb shell pm install-existing com.qualcomm.qti.remoteSimlockAuth
adb shell pm install-existing com.motorola.settings
adb shell pm install-existing com.motorola.omadm.service
adb shell pm install-existing com.inmobi.installer
adb shell pm install-existing com.motorola.setup.overlay.tmo
adb shell pm install-existing com.motorola.android.launcher.overlay.tmo.rcs.apptray
adb shell pm install-existing com.qualcomm.qti.xrcb
adb shell pm install-existing com.motorola.hiddenmenuapp
adb shell pm install-existing com.motorola.android.systemui.overlay.sprint
adb shell pm install-existing com.android.wallpapercropper
adb shell pm install-existing com.vzw.apnlib
adb shell pm install-existing com.motorola.android.overlay.common
adb shell pm install-existing com.google.android.overlay.gmsconfig.geotz
adb shell pm install-existing com.android.theme.icon.pebble
adb shell pm install-existing com.android.internal.systemui.navbar.gestural
adb shell pm install-existing com.motorola.bug2go
adb shell pm install-existing com.google.android.calculator
adb shell pm install-existing com.android.settings.intelligence
adb shell pm install-existing com.aura.oobe.motorola
adb shell pm install-existing com.motorola.comcast.settings.extensions
adb shell pm install-existing com.qualcomm.timeservice
adb shell pm install-existing com.motorola.android.launcher.overlay.koodo
adb shell pm install-existing com.motorola.android.launcher.overlay.assurance.rcs.apptray
adb shell pm install-existing com.google.android.overlay.gmsconfig.personalsafety
adb shell pm install-existing com.qualcomm.wfd.service
adb shell pm install-existing com.motorola.systemserver
adb shell pm install-existing com.motorola.genie
adb shell pm install-existing com.motorola.android.launcher.overlay.tmonosim.rcs.apptray
adb shell pm install-existing com.google.android.federatedcompute
adb shell pm install-existing vendor.qti.imsrcs
adb shell pm install-existing com.google.android.webview
adb shell pm install-existing com.google.android.sdksandbox
adb shell pm install-existing com.motorola.motosignature.app
adb shell pm install-existing com.motorola.android.overlay.tmo
adb shell pm install-existing com.google.android.cellbroadcastservice
adb shell pm install-existing com.motorola.fmplayer
adb shell pm install-existing com.android.internal.systemui.navbar.threebutton
adb shell pm install-existing com.android.egg
adb shell pm install-existing com.motorola.appforecast
adb shell pm install-existing com.google.android.overlay.modules.modulemetadata.forframework
adb shell pm install-existing com.motorola.nfc
adb shell pm install-existing com.android.providers.settings.auto_generated_rro_product__
adb shell pm install-existing com.oem.euiccpartnerapp.overlay.att
adb shell pm install-existing com.google.android.packageinstaller
adb shell pm install-existing com.android.se
adb shell pm install-existing com.google.android.apps.youtube.music
adb shell pm install-existing com.android.internal.systemui.navbar.hidegestural
adb shell pm install-existing com.android.stk
adb shell pm install-existing com.vzw.apnservice
adb shell pm install-existing com.motorola.android.fmradio
adb shell pm install-existing com.android.bips
adb shell pm install-existing com.qualcomm.qti.telephonyservice
adb shell pm install-existing com.google.android.partnersetup
adb shell pm install-existing com.google.android.apps.gcs
adb shell pm install-existing com.google.android.projection.gearhead
adb shell pm install-existing com.motorola.launcherconfig.overlay.amxcl
adb shell pm install-existing com.tmobile.rsuadapter.qualcomm
adb shell pm install-existing com.motorola.default.ringtones.overlay.metro.usku
adb shell pm install-existing com.motorola.launcherconfig.overlay.fi
adb shell pm install-existing com.motorola.rcsConfigService
adb shell pm install-existing com.google.android.apps.carrier.carrierwifi
adb shell pm install-existing com.motorola.launcherconfig.overlay.amxco
adb shell pm install-existing com.motorola.android.systemui.overlay.usc
adb shell pm install-existing com.google.android.feedback
adb shell pm install-existing org.codeaurora.ims
adb shell pm install-existing com.verizon.loginengine.unbranded
adb shell pm install-existing com.motorola.livewallpaper3
adb shell pm install-existing com.motorola.default.ringtones.overlay.tmo.usku
adb shell pm install-existing com.aura.services.tmobile
adb shell pm install-existing com.motorola.setup.overlay.att
adb shell pm install-existing com.android.devicelockcontroller
adb shell pm install-existing com.motorola.gamemode
adb shell pm install-existing com.motorola.att.sim.extensions
adb shell pm install-existing com.google.android.inputmethod.latin
adb shell pm install-existing com.motorola.systemui.desk
adb shell pm install-existing com.android.wifi.resources.overlay.WifiTmoOverlay
adb shell pm install-existing com.motorola.launcherconfig.overlay.attpre
adb shell pm install-existing com.android.providers.downloads.ui
adb shell pm install-existing com.android.ons
adb shell pm install-existing com.google.android.healthconnect.controller
adb shell pm install-existing com.motorola.android.launcher.overlay.att
adb shell pm install-existing com.oem.euiccpartnerapp.overlay.vzw
adb shell pm install-existing com.motorola.slpc_sys
adb shell pm install-existing com.motorola.android.launcher.overlay.att.apptray
adb shell pm install-existing com.google.android.setupwizard
adb shell pm install-existing com.motorola.android.providers.settings
adb shell pm install-existing com.android.simappdialog
adb shell pm install-existing com.android.wallpaper.livepicker
adb shell pm install-existing com.motorola.actions
adb shell pm install-existing com.android.internal.display.cutout.emulation.waterfall
adb shell pm install-existing com.android.cellbroadcast.overlay
adb shell pm install-existing com.motorola.android.launcher.overlay.metropcs.rcs.apptray
adb shell pm install-existing com.cricketwireless.thescoop
adb shell pm install-existing com.motorola.launcherconfig
adb shell pm install-existing com.motorola.android.coresettingsext.overlay.pnangn
adb shell pm install-existing com.google.android.overlay.modules.ext.services
adb shell pm install-existing com.android.theme.icon.round
adb shell pm install-existing com.motorola.android.launcher.overlay.applabeltwolines
adb shell pm install-existing com.android.traceur
adb shell pm install-existing com.att.iqi
adb shell pm install-existing com.google.android.apps.messaging
adb shell pm install-existing com.oem.euiccpartnerapp.overlay.usc
adb shell pm install-existing com.motorola.discovery
adb shell pm install-existing com.motorola.launcherconfig.overlay.boost
adb shell pm install-existing com.metropcs.metrozone
adb shell pm install-existing com.tmobile.m1
adb shell pm install-existing com.android.location.fused
adb shell pm install-existing com.android.cellbroadcastreceiver
adb shell pm install-existing com.google.android.googlequicksearchbox
adb shell pm install-existing com.google.android.modulemetadata
adb shell pm install-existing com.motorola.setup
adb shell pm install-existing com.android.wifi.resources.overlay.motCommon
adb shell pm install-existing com.google.android.ext.services
adb shell pm install-existing com.motorola.nfwlocationattribution
adb shell pm install-existing com.google.android.configupdater
adb shell pm install-existing com.motorola.sstservice
adb shell pm install-existing com.dish.vvm
adb shell pm install-existing com.motorola.android.launcher.overlay.amx
adb shell pm install-existing com.google.android.gms.supervision
adb shell pm install-existing com.google.android.apps.photos
adb shell pm install-existing com.motorola.mototour
adb shell pm install-existing com.att.personalcloud
adb shell pm install-existing com.qualcomm.qti.workloadclassifier
adb shell pm install-existing com.android.internal.display.cutout.emulation.corner
adb shell pm install-existing com.google.android.gms
adb shell pm install-existing com.lenovo.lsf.user
adb shell pm install-existing com.oem.euiccpartnerapp.overlay.na
adb shell pm install-existing com.motorola.android.systemui.overlay.tmo
adb shell pm install-existing com.tmobile.pr.mytmobile
adb shell pm install-existing com.android.printspooler
adb shell pm install-existing com.motorola.bach.modemstats
adb shell pm install-existing com.qualcomm.qti.uim
adb shell pm install-existing com.motorola.revoker.services
adb shell pm install-existing com.facebook.system
adb shell pm install-existing com.android.soundpicker
adb shell pm install-existing com.google.mainline.telemetry
adb shell pm install-existing com.motorola.spaces
adb shell pm install-existing com.motorola.camera3.content.ai
adb shell pm install-existing com.aura.oobe.solutions
adb shell pm install-existing com.oem.euiccpartnerapp.overlay.retca
adb shell pm install-existing com.oem.euiccpartnerapp.overlay.dish
adb shell pm install-existing com.android.externalstorage
adb shell pm install-existing com.motorola.enterprise.service
adb shell pm install-existing com.motorola.spectrum.setup.extensions
adb shell pm install-existing com.android.server.telecom
adb shell pm install-existing com.motorola.timeweatherwidget
adb shell pm install-existing com.motorola.motocare
adb shell pm install-existing com.google.android.providers.media.module
adb shell pm install-existing com.android.providers.settings.overlay.tmo
adb shell pm install-existing com.motorola.android.overlay.qcom.common
adb shell pm install-existing com.motorola.att.phone.extensions
adb shell pm install-existing com.tmobile.echolocate.system
adb shell pm install-existing com.android.calllogbackup
adb shell pm install-existing com.dish.wireless.installer
adb shell pm install-existing com.qualcomm.atfwd
adb shell pm install-existing com.motorola.callredirectionservice
adb shell pm install-existing com.linkedin.android
adb shell pm install-existing com.google.android.overlay.gmsconfig.comms
adb shell pm install-existing com.motorola.omadm.dish
adb shell pm install-existing com.motorola.setup.overlay.att.simoobe
adb shell pm install-existing com.android.dreams.basic
adb shell pm install-existing com.google.android.calendar
adb shell pm install-existing com.google.android.apps.youtube.music.setupwizard
adb shell pm install-existing com.motorola.android.launcher.overlay.telus
adb shell pm install-existing com.google.android.contacts
adb shell pm install-existing com.android.mms.service
adb shell pm install-existing com.google.android.cellbroadcastreceiver
adb shell pm install-existing com.motorola.msimsettings.overlay
adb shell pm install-existing com.motorola.launcherconfig.overlay.amxla
adb shell pm install-existing android.auto_generated_rro_vendor__
adb shell pm install-existing com.google.android.apps.wellbeing
adb shell pm install-existing com.motorola.android.systemui.overlay.att
adb shell pm install-existing com.qualcomm.qti.devicestatisticsservice
adb shell pm install-existing com.android.virtualmachine.res
adb shell pm install-existing com.digitalturbine.android.apps.news.att
adb shell pm install-existing com.motorola.contacts.preloadcontacts.overlay.vzw
adb shell pm install-existing com.google.android.adservices.api
adb shell pm install-existing com.motorola.dynamicvolumeoverlay
adb shell pm install-existing com.android.inputdevices
adb shell pm install-existing com.qti.qualcomm.datastatusnotification
adb shell pm install-existing com.android.theme.font.Exo2Regular
adb shell pm install-existing com.qti.dpmserviceapp
adb shell pm install-existing com.google.android.onetimeinitializer
adb shell pm install-existing com.google.android.permissioncontroller
adb shell pm install-existing com.motorola.android.launcher.overlay.motolauncheroverlayna
adb shell pm install-existing com.motorola.launcherconfig.overlay.amxmx
adb shell pm install-existing com.glance.lockscreenM
adb shell pm install-existing com.motorola.omadm.vzw
adb shell pm install-existing com.google.android.overlay.modules.documentsui
adb shell pm install-existing cci.usage
adb shell pm install-existing com.android.managedprovisioning
adb shell pm install-existing com.motorola.securityhub
adb shell pm install-existing com.motorola.imagertuning_u
adb shell pm install-existing com.oem.euiccpartnerapp.overlay.tmo
adb shell pm install-existing com.motorola.vzw.pco.extensions.pcoreceiver
adb shell pm install-existing com.att.mobile.android.vvm
adb shell pm install-existing com.google.android.deskclock
adb shell pm install-existing com.google.android.gsf
adb shell pm install-existing com.nuance.nmc.sihome.metropcs
adb shell pm install-existing com.att.csoiam.mobilekey
adb shell pm install-existing com.motorola.launcherconfig.overlay.att
adb shell pm install-existing com.android.internal.display.cutout.emulation.double
adb shell pm install-existing com.motorola.thermalservice.overlay.tmo
adb shell pm install-existing com.motorola.android.settings.overlay.tmo
adb shell pm install-existing com.google.android.health.connect.backuprestore
adb shell pm install-existing com.qualcomm.qti.xrvd.service
adb shell pm install-existing com.motorola.android.nativedropboxagent
adb shell pm install-existing com.motorola.motcameradesktop
adb shell pm install-existing com.cricketwireless.minus
adb shell pm install-existing com.motorola.paks.notification
adb shell pm install-existing android.autoinstalls.config.motorola.layout
adb shell pm install-existing com.google.android.apps.docs.editors.sheets
adb shell pm install-existing com.android.systemui
adb shell pm install-existing com.google.ar.core
adb shell pm install-existing com.motorola.coresettingsext
adb shell pm install-existing com.google.android.dialer
adb shell pm install-existing com.motorola.dolby.dolbyui
adb shell pm install-existing com.motorola.launcherconfig.overlay.amxpe
adb shell pm install-existing com.motorola.carrierconfig
adb shell pm install-existing com.qualcomm.qti.uceShimService
adb shell pm install-existing com.android.role.notes.enabled
adb shell pm install-existing com.anonyome.mysudo
adb shell pm install-existing com.motorola.overlay.launcher3
adb shell pm install-existing com.motorola.attvowifi
adb shell pm install-existing com.google.mainline.adservices
adb shell pm install-existing com.motorola.setup.auto_generated_rro_product__
adb shell pm install-existing com.android.hotwordenrollment.okgoogle
adb shell pm install-existing com.bluetooth.aptxmode
adb shell pm install-existing com.motorola.android.launcher.overlay.retail.row
adb shell pm install-existing com.motorola.android.coresettingsext.overlay.disabletappingthedisplay
adb shell pm install-existing com.android.theme.icon.roundedrect
adb shell pm install-existing com.google.android.apps.wallpaper
adb shell pm install-existing com.att.dh
adb shell pm install-existing com.motorola.setup.overlay.boost
adb shell pm install-existing com.motorola.android.fota
adb shell pm install-existing com.motorola.smart5g
adb shell pm install-existing com.motorola.android.providers.settings.auto_generated_rro_product__
adb shell pm install-existing com.android.wallpaperbackup
adb shell pm install-existing com.motorola.setup.overlay.primaryesim
adb shell pm install-existing com.android.localtransport
adb shell pm install-existing com.motorola.contacts.preloadcontacts
adb shell pm install-existing com.android.rkpdapp
adb shell pm install-existing com.android.hotwordenrollment.xgoogle
adb shell pm install-existing com.motorola.android.systemui.overlay.vzw
adb shell pm install-existing com.tmobile.echolocate
adb shell pm install-existing com.qualcomm.qti.dynamicddsservice
adb shell pm install-existing com.google.android.apps.walletnfcrel
adb shell pm install-existing com.android.internal.display.cutout.emulation.noCutout
adb shell pm install-existing com.motorola.freeform
adb shell pm install-existing com.motorola.enterprise.adapter.service
adb shell pm install-existing com.android.pacprocessor
adb shell pm install-existing com.motorola.android.settings.overlay.att
adb shell pm install-existing com.tmobile.dm.ms.services
adb shell pm install-existing com.motorola.android.providers.settings.overlay.tmo
adb shell pm install-existing com.motorola.launcherconfig.overlay.tmo
adb shell pm install-existing com.google.android.safetycenter.resources
adb shell pm install-existing com.android.internal.display.cutout.emulation.hole
adb shell pm install-existing com.android.settings
adb shell pm install-existing com.android.internal.systemui.navbar.gestural_narrow_back
adb shell pm install-existing com.android.internal.display.cutout.emulation.tall
adb shell pm install-existing com.google.android.networkstack.tethering
adb shell pm install-existing com.android.cameraextensions
adb shell pm install-existing com.motorola.demo
adb shell pm install-existing com.android.carrierconfig
adb shell pm install-existing com.android.internal.systemui.navbar.gestural_wide_back
adb shell pm install-existing com.aura.oobe.dish
adb shell pm install-existing com.motorola.setup.overlay.pai
adb shell pm install-existing com.google.android.videos
adb shell pm install-existing com.google.android.ext.shared
adb shell pm install-existing com.motorola.launcherconfig.overlay.cricket
adb shell pm install-existing com.motorola.tmo.setupext
adb shell pm install-existing com.motorola.securityhubext
adb shell pm install-existing com.motorola.android.settings.overlay.global
adb shell pm install-existing com.android.chrome
adb shell pm install-existing com.qualcomm.qcrilmsgtunnel
adb shell pm install-existing com.motorola.easyprefix
adb shell pm install-existing com.facebook.services
adb shell pm install-existing com.motorola.personalize
adb shell pm install-existing com.google.android.apps.maps
adb shell pm install-existing com.motorola.android.settings.overlay.fps.side
adb shell pm install-existing com.motorola.brapps
adb shell pm install-existing com.google.android.apps.chromecast.app
adb shell pm install-existing com.google.android.as
adb shell pm install-existing com.android.internal.systemui.navbar.transparent
adb shell pm install-existing com.motorola.thermalservice
adb shell pm install-existing com.att.deviceunlock
adb shell pm install-existing com.inmobi.weather
adb shell pm install-existing com.motorola.android.networkstack.overlay.mcc460
adb shell pm install-existing com.google.android.marvin.talkback
adb shell pm install-existing com.motorola.android.launcher.overlay.boost.apptray
adb shell pm install-existing com.ironsrc.aura.tmo
adb shell pm install-existing com.google.android.wifi.resources
adb shell pm install-existing com.android.intentresolver
adb shell pm install-existing com.google.android.apps.docs
adb shell pm install-existing com.motorola.android.server.telecom.overlay.tmo
adb shell pm install-existing com.motorola.android.launcher.overlay.mvnos
adb shell pm install-existing com.android.dialer
adb shell pm install-existing com.android.certinstaller
adb shell pm install-existing com.oem.euiccpartnerapp
adb shell pm install-existing com.google.android.apps.safetyhub
adb shell pm install-existing com.dish.wireless.carrierapp
adb shell pm install-existing com.oem.euiccpartnerapp.overlay.cc
adb shell pm install-existing com.google.android.apps.restore
adb shell pm install-existing com.qualcomm.atfwd2
adb shell pm install-existing com.motorola.mobiledesktop.core
adb shell pm install-existing com.android.providers.telephony
adb shell pm install-existing com.android.cellbroadcastservice.overlay
adb shell pm install-existing com.motorola.faceunlock
adb shell pm install-existing com.tmobile.pr.adapt
adb shell pm install-existing com.android.theme.font.RobotoSlabRegular
adb shell pm install-existing com.motorola.android.overlay.lpptoga
adb shell pm install-existing com.android.settings.auto_generated_rro_product__
adb shell pm install-existing com.motorola.launcherconfig.overlay.usc
adb shell pm install-existing com.android.providers.settings
adb shell pm install-existing com.android.phone
adb shell pm install-existing com.android.internal.systemui.navbar.gestural_extra_wide_back
adb shell pm install-existing com.google.android.apps.subscriptions.red
adb shell pm install-existing com.aurora.store
adb shell pm install-existing com.google.android.as.oss
adb shell pm install-existing com.motorola.appdirectedsmsproxy
adb shell pm install-existing com.android.contacts
adb shell pm install-existing com.tmobile.dm.cm
adb shell pm install-existing com.android.vpndialogs
adb shell pm install-existing com.android.uwb.resources
adb shell pm install-existing com.mizmowireless.acctmgt
adb shell pm install-existing com.android.systemui.plugin.globalactions.wallet
adb shell pm install-existing com.ironsrc.aura.appmanager.tmo
adb shell pm install-existing com.google.android.overlay.gmsconfig.photos
adb shell pm install-existing com.google.android.apps.docs.editors.docs
adb shell pm install-existing com.google.android.tts
adb shell pm install-existing com.motorola.dciservice
adb shell pm install-existing com.qualcomm.qtil.btdsda
adb shell pm install-existing com.motorola.motocit
adb shell pm install-existing com.android.phone.overlay.common
adb shell pm install-existing com.tmobile.rsusrv
adb shell pm install-existing com.android.htmlviewer
adb shell pm install-existing com.android.vending
adb shell pm install-existing com.google.android.overlay.modules.captiveportallogin.forframework
adb shell pm install-existing com.motorola.android.launcher.overlay.animation.scale
adb shell pm install-existing com.google.android.apps.turbo
adb shell pm install-existing com.motorola.camera3
adb shell pm install-existing com.motorola.audiorecorder
adb shell pm install-existing com.google.android.overlay.gmsconfig.gsa
adb shell pm install-existing com.android.providers.userdictionary
adb shell pm install-existing com.google.android.overlay.gmsconfig.common
adb shell pm install-existing com.android.cts.ctsshim
adb shell pm install-existing com.android.bluetooth
adb shell pm install-existing com.google.android.wfcactivation
adb shell pm install-existing com.motorola.android.providers.settings.overlay.dppnone
adb shell pm install-existing com.motorola.motosignature2.app
adb shell pm install-existing com.android.storagemanager
adb shell pm install-existing com.motorola.android.overlay.crystaltalkai
adb shell pm install-existing com.android.phone.overlay.carriersettings
adb shell pm install-existing com.motorola.securevault
adb shell pm install-existing com.android.systemui.auto_generated_rro_product__
adb shell pm install-existing com.motorola.android.overlay.tmo.usku
adb shell pm install-existing com.motorola.help.extlog
adb shell pm install-existing com.android.providers.partnerbookmarks
adb shell pm install-existing com.amazon.appmanager
adb shell pm install-existing com.motorola.lifetimedata
adb shell pm install-existing com.motorola.launcher3
adb shell pm install-existing com.google.ambient.streaming
adb shell pm install-existing com.google.android.euicc
adb shell pm install-existing com.facebook.katana
adb shell pm install-existing com.google.android.carrier
adb shell pm install-existing com.android.dynsystem
adb shell pm install-existing com.android.providers.telephony.overlay.carriersettings
adb shell pm install-existing com.google.android.connectivity.resources
adb shell pm install-existing com.google.android.youtube
adb shell pm install-existing com.tmobile.rsuapp
adb shell pm install-existing com.motorola.ccc.ota
adb shell pm install-existing com.motorola.omadm.att
