#!/bin/bash
adb shell pm uninstall -k --user 0 com.motorola.audiorecorder > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.motosignature2.app > /dev/null
adb shell pm uninstall -k --user 0 org.codeaurora.ims > /dev/null
adb shell pm uninstall -k --user 0 com.aurora.store > /dev/null
adb shell pm uninstall -k --user 0 com.facebook.appmanager > /dev/null
adb shell pm uninstall -k --user 0 com.facebook.system > /dev/null
adb shell pm uninstall -k --user 0 com.facebook.services > /dev/null
adb shell pm uninstall -k --user 0 com.facebook.katana > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.livewallpaper3 > /dev/null
adb shell pm uninstall -k --user 0 com.linkedin.android > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.dolby.dolbyui > /dev/null
adb shell pm uninstall -k --user 0 com.dolby.daxservice > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.fitness > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.printservice.recommendation > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.slides > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.googleassistant > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.tachyon > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.gm > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.magazines > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.youtube.music > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.feedback > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.healthconnect.controller > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.setupwizard > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.messaging > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.photos > /dev/null
adb shell pm uninstall -k --user 0 com.google.mainline.telemetry > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.calendar > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.youtube.music.setupwizard > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.contacts > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.wellbeing > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.deskclock > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.health.connect.backuprestore > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.sheets > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.walletnfcrel > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.videos > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.maps > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.chromecast.app > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.marvin.talkback > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.docs > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.docs > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.tts > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.turbo > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.youtube > /dev/null
adb shell pm uninstall -k --user 0 com.android.chrome > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.android.providers.chromehomepage > /dev/null
adb shell pm uninstall -k --user 0 com.metropcs.metrozone > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.subscriptions.red > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.spaces > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.ccc.notification > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.securityhub > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.gamemode > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.help > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.help.extlog > /dev/null
adb shell pm uninstall -k --user 0 com.android.vending > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.partnersetup > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.dialer > /dev/null
adb shell pm uninstall -k --user 0 com.android.calllogbackup > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.nbu.files > /dev/null
adb shell pm uninstall -k --user 0 com.google.ar.core > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.apps.restore > /dev/null
adb shell pm uninstall -k --user 0 com.google.android.gms.location.history > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.moto > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.genie > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.timeweatherwidget > /dev/null
adb shell pm uninstall -k --user 0 com.inmobi.weather > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.fmplayer > /dev/null
adb shell pm uninstall -k --user 0 com.motorola.android.fmradio > /dev/null
