#!/bin/bash
adb shell pm install-existing com.motorola.audiorecorder
adb shell pm install-existing com.motorola.motosignature2.app
adb shell pm install-existing org.codeaurora.ims
adb shell pm install-existing com.aurora.store
adb shell pm install-existing com.facebook.appmanager
adb shell pm install-existing com.facebook.system
adb shell pm install-existing com.facebook.services
adb shell pm install-existing com.facebook.katana
adb shell pm install-existing com.motorola.livewallpaper3
adb shell pm install-existing com.linkedin.android
adb shell pm install-existing com.motorola.dolby.dolbyui
adb shell pm install-existing com.dolby.daxservice
adb shell pm install-existing com.google.android.apps.fitness
adb shell pm install-existing com.google.android.printservice.recommendation
adb shell pm install-existing com.google.android.apps.docs.editors.slides
adb shell pm install-existing com.google.android.apps.googleassistant
adb shell pm install-existing com.google.android.apps.tachyon
adb shell pm install-existing com.google.android.gm
adb shell pm install-existing com.google.android.apps.magazines
adb shell pm install-existing com.google.android.apps.youtube.music
adb shell pm install-existing com.google.android.feedback
adb shell pm install-existing com.google.android.healthconnect.controller
adb shell pm install-existing com.google.android.setupwizard
adb shell pm install-existing com.google.android.apps.messaging
adb shell pm install-existing com.google.android.googlequicksearchbox
adb shell pm install-existing com.google.android.apps.photos
adb shell pm install-existing com.google.mainline.telemetry
adb shell pm install-existing com.google.android.calendar
adb shell pm install-existing com.google.android.apps.youtube.music.setupwizard
adb shell pm install-existing com.google.android.contacts
adb shell pm install-existing com.google.android.apps.wellbeing
adb shell pm install-existing com.google.android.deskclock
adb shell pm install-existing com.google.android.health.connect.backuprestore
adb shell pm install-existing com.google.android.apps.docs.editors.sheets
adb shell pm install-existing com.google.android.apps.walletnfcrel
adb shell pm install-existing com.google.android.videos
adb shell pm install-existing com.google.android.apps.maps
adb shell pm install-existing com.google.android.apps.chromecast.app
adb shell pm install-existing com.google.android.marvin.talkback
adb shell pm install-existing com.google.android.apps.docs
adb shell pm install-existing com.google.android.apps.docs.editors.docs
adb shell pm install-existing com.google.android.tts
adb shell pm install-existing com.google.android.apps.turbo
adb shell pm install-existing com.google.android.youtube
adb shell pm install-existing com.android.chrome
adb shell pm install-existing com.motorola.android.providers.chromehomepage
adb shell pm install-existing com.metropcs.metrozone
adb shell pm install-existing com.google.android.apps.subscriptions.red
adb shell pm install-existing com.motorola.spaces
adb shell pm install-existing com.motorola.ccc.notification
adb shell pm install-existing com.motorola.securityhub
adb shell pm install-existing com.motorola.gamemode
adb shell pm install-existing com.motorola.help
adb shell pm install-existing com.motorola.help.extlog
adb shell pm install-existing com.android.vending
adb shell pm install-existing com.google.android.partnersetup
adb shell pm install-existing com.google.android.dialer
adb shell pm install-existing com.android.calllogbackup
adb shell pm install-existing com.google.android.apps.nbu.files
adb shell pm install-existing com.google.ar.core
adb shell pm install-existing com.google.android.apps.restore
adb shell pm install-existing com.google.android.gms.location.history
adb shell pm install-existing com.motorola.moto
adb shell pm install-existing com.motorola.genie
adb shell pm install-existing com.motorola.timeweatherwidget
adb shell pm install-existing com.inmobi.weather
adb shell pm install-existing com.motorola.fmplayer
adb shell pm install-existing com.motorola.android.fmradio
